// import type { Metadata } from "next";
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from "@clerk/nextjs";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider";
// // import { Navbar } from "@/components/Navbar";
// import Navbar from "@/components/Navbar";
// import Sidebar from "@/components/Sidebar";

// import { syncUser } from "@/actions/user.action";
// import { currentUser } from "@clerk/nextjs/server";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Clerk Next.js Quickstart",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   // export default function RootLayout(
//   //   { children },
//   //   : Readonly<{
//   //       children: React.ReactNode;
//   //   }>
//   // ) {
//   //   return (
//   //     <html lang="en">
//   //       <body>{children}</body>
//   //     </html>
//   //   );
//   // }

//   // export default function RootLayout(
//   //   { children },
//   //   : Readonly<{
//   //     //   children: React.ReactNode;
//   //   }>
//   // ) {
//   //
//   // const user = await currentUser();
//   // if (user) await syncUser(); // POST

//   return (
//     <ClerkProvider>
//       <html lang="en" suppressHydrationWarning>
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
//             <div className="min-h-screen">
//               <Navbar />
//               <main className="py-8">
//                 <div className="max-w-7x1 mx-auto px-4">
//                   <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
//                     <div className="hidden lg:block lg:col-span-3">
//                       <Sidebar />
//                     </div>
//                   </div>
//                 </div>
//                 <div className="lg:col-span-9">{children}</div>
//               </main>
//             </div>
//           </ThemeProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "react-hot-toast";
import { currentUser } from "@clerk/nextjs/server";
import prisma from "@/lib/prisma";
import { auth } from "@clerk/nextjs/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Socially",
  description: "A modern social media application powered by Next.js",
};

export default async function RootLayout({
  children,
  // }: Readonly<{
  //   children: React.ReactNode;
  // }>) {
}: {
  children: React.ReactNode;
}) {
  // const user = await currentUser();
  // const { userId } = await auth();

  // if (!userId || !user) return;
  // const existingUser = await prisma.user.findUnique({
  //   where: {
  //     clerkId: userId,
  //   },
  // });

  // if (user) {
  //   // await prisma.user.upsert({
  //   //   where: { clerkId: user.id },
  //   // });
  //   const dbUser = await prisma.user.create({
  //     // const dbUser = await prisma.user.upsert({
  //     data: {
  //       clerkId: userId,
  //       name: `${user.firstName || ""} ${user.lastName || ""}`,
  //     },
  //   });
  // }
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-screen">
              <Navbar />

              <main className="py-8">
                {/* container to center the content */}
                <div className="max-w-7xl mx-auto px-4">
                  <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                    <div className="hidden lg:block lg:col-span-3">
                      <Sidebar />
                    </div>
                    <div className="lg:col-span-9">{children}</div>
                  </div>
                </div>
              </main>
            </div>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
